### ISSUE TITLE
Id3 Battery withe 12 cells

### ISSUE THREAD

**Issue by Michi202020** [stuartpittaway/diyBMSv4#117]
Hello,
I am new hear in Github. My English is not the best but I hope you understand me.
I have 14 peases from this block and I will create homestorage withe your system. At this time I have install 3x6,85kwh Id3 and 2x6,85kwh.
The big problem is the wire ring from the battery to your v4. 4 board. My idea is that you can create a board from 6 cells to 16 cells and in the software you can switch on or off the Funktion how many cells are installed. For example I install on the 16 cells only the Id3 12s and the last 4 is deaktiviert. I think it's better than on the market are not enough attiny841 and one chip for 16 cells are easy to create. I have one gay more he will also build storage withe your system.
Pleas let me now what can we do or I can create the board but I need only a person what can write the code. I am not good in this.

Best Regards
Michael

**Comment by fhorst1** [comment]
Dear Michael,

Each cell can function without any BMS. You do need to manually watch it
like a hawk and manage it accordingly..

DIYBMS works with 1 cell module per series set (can contain more then 1
cell in parallel)

Removing or disabling a cell module, see first comment ..
You need to do manually.

The global chip shortage hurts all sectors, including this DIY part.

Yes, they can re-invent cars to function without the chip that has
shortage, they don't.
Much cheaper, safer, more efficient is to simply wait for the chips.

Lucky for us, there are MANY different BMS available, many lower costs then
the DIYBMS.

While most lack power in the balance part (Daly does only 0.08A), an
additional balancer is cheap and widely available.

With higher capacity setups, you where already using contactors instead of
MOSFET based.

Any 10A BMS can manage 1000A installation, if you let the MOSFET of the BMS
control the contactor.
(Using a small switch to power the high capacity one)

It does not have to cost a lot.

Obviously, the design of DIYBMS didn't forsee that the widely available and
known attiny would get a shortage.

Change to different chip isn't that easy.
Change to totally different system and setup (not individual cell modules)
will take a long time and is a totally different product.

Many DIY members feel and share your pain, waiting for their backorder for
months and months.

I was "lucky" and obtained for my 4 X 280Ah sets enough attiny chips to
populate a 5th one if needed.

Yet....
As BMS is so crazy important.
I have all 4 also equipped with Jkong 2A active balancer BMS.

Redundancy is key :-)

4 X 14kwh isn't cheap and any sunny day can push a cell beyond its maximal
voltage if there is imbalance.

My motto:
Better safe than sorry.

Cheap BMS, 100A contactor and 1.2A balancer can be bought for around $40-75
(globally from Asia) (S16 setup)
DIYBMS won't be cheaper.

If you want to have the same functionality...
Professional alternative is quickly +$750,-

Re-writing the software to function with different design of PCB and/or
different chipset will take weeks, months probably. With lots of testing,
magic smoke and buckets of patience.
It's not that easy as you hope it would be.

I take this opportunity to thank Stuart for all his time and effort and all
the others in the community that helps.

Probably not the response you hoped for, it can give you the tools to
proceed (for now) without DIYBMS, and get "standard" product to protect and
use your cells.

Shortages don't last decades.

In 18-24 months there will be enough attiny available at a price of under
$1 (back to $0.80?)

Unless China goes to war also...
Then not having attiny is a minor problem :)

Frank

**Comment by stuartpittaway** [comment]
With the existing module design having very short wires to the cells is critical.

They must also not share the same wires.

You will run into balance and voltage reading erros if this isn't followed.
